id: https://raw.githubusercontent.com/datajoint/datajoint-file-validator/main/manifests/demo_bob_lab_frames_v0.1
name: bob_lab_frames
version: 0.1.0
description: Example of a fileset type for a Bob Lab fileset
author:
  name: Ethan Ho
  email: ***REMOVED***
rules:
  - name: num_files_constraint
    description: Check that there are between 1 and 5 files in the directory
    count_min: 1
    count_max: 5
  - name: num_files_per_subdir
    description: >
      Check that each subdirectory has between 1 and 100 files
      and that subdirectories only contain .mp4 files.
    query:
      path: "/*"
      type: directory
    rules:
      - name: count_per_subdir
        # Here, the query ("/**") is relative to the sub-directory
        # instead of the root.
        query: "/"
        count_min: 1
        count_max: 100
      - name: check_file_type
        # query: "/**" is implicit here
        regex: "^.*\\.mp4$"
  - name: file_type_in_subdir
    description: Check that each subdirectory has exactly one obs.md file
    query:
      # Instead of path, regex, or type, we can write a custom query function
      # that filters the items that are passed to the constraints.
      eval: |
        def get_subdirs(results: list[dict]) -> list[bool]:
          return [True for r in results if r['type'] == 'directory' else False]
    rules:
      - query: "/obs.md"
        description: "There is exactly one obs.md"
      - query: "obs.md"
        description: "Another way to write the above"
      - query: "obs.md"
        description: "Yet another way to write this rule"
        count_min: 1
        count_max: 1